const sections=[
  {title: "HyperText Markup Language",
   paragraphOne: "HTML is the backbone of all websites, a skeleton to which the rest of the parts are affixed. All of the content lives here.",
   paragraphTwo: "HTML is syntacically tagged up with tags. There are many different kinds of tags. Each tag tells the browser what kind of content goes between each tag. For example a header tag indicates that the enclosed text is a title for a page.",
   code: "Example: &lth1&gtTitle of Webpage&lt/h1&gt",
   list: ["Opening tag","Closing tag", "Type of tag", "Links", "Font"]},
  {title: "Cascading Style Sheets",
   paragraphOne: "Basic web pages are boring and contain nothing but text. The way a webpage looks, the style of it, is modified by CSS. The appearance or skin of a site is made and lives here.",
   paragraphTwo: "CSS is a powerful and useful conterpart to HTML. It can do as little as change color of font to as much as create animations and much more.",
   code: "To change all elements to border-box sizing:<br><br> * {<br>box-sizing: border-box;<br>}",
   list: ["Selectors","Bracket Notation", "Inheritance", "Specificity", "Pseudo Class"]},
  {title: "JavaScript",
   paragraphOne: "If HTML is the bones and CSS is the skin, then Javascript is the brains of a website. Any interactivity other than basic clicking on buttons and hovering over elements is done here.",
   paragraphTwo: "Javascript does or some framework around JavaScript does all of the heavy lifting for webpages and is a basic requirement to make sites live.",
   code: "Simple Example:<br>console.log('Hello World') will type 'Hello World' to the console"},
  {title: "The Document Object Model",
   paragraphOne: "The DOM is how javascript talks to the webpage. Once the JavaScript and DOM are linked, all mannner of manipulation of the page can be performed.",
   paragraphTwo: "DOM manipulation is the first thing one can do once JavaScript is learned.",
   code: "Example:<br>document.createElement('h1')<br>Will create an h1 element."},
  {title: "Programming",
   paragraphOne: "Programming is all about making the computer do the work for you. Once a program is set up and free from bugs, it will run the same way indefinitly until it finishes.",
   paragraphTwo: "The key to good progrmming is to not repeat code. If you are writing the same bit of code repeatedly, you can be doing better programming.",
   code: "Example:<br>document.createElement('li')<br>Creates a list item. If you want more than one list item, you will have to repeat the code.<br>document.createElement('li')<br>That is unless you use a programming loop.<br>for(let element in array){<br>document.createElement('li')<br>}<br>Will create a li element for every element in array."},
  {title: "Responsive Design",
   paragraphOne: "Finally, once all of the content for a website has been created, it has to look good across all devices to maintain professionalism.",
   paragraphTwo: "With the emerging frequency that people access websites on mobile devices, repsonsive design is even more important than ever.",
   code: "<h3>Example:</h3><br>Most repsonsive design elements occur in CSS<br>@media screen and(max-width: 470px){<br>h1 {<br>color: red;}<br>}<br>Will paint all h1 elements red as long as the width of the screen is less than 470 pixels wide."}
];
//Additional sections can be added by simply creating another "sections" object as long as it has the same keys.
